---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set Default Policy to Deny Incoming
  ufw:
    direction: incoming
    policy: deny

- name: allow SSH with Rate Limting
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
  loop: "{{allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled

- name: Panic Now
  ufw:
    state: enabled
    policy: deny
  when: panic_mode | bool

- name: enable Panic
  ansible.builtin.command: iptables -P INPUT DROP
  when: panic_mode | bool

- name: panic
  ansible.builtin.command: iptables -P FORWARD DROP
  when: panic_mode | bool

- name: panic
  ansible.builtin.command: iptables -P OUTPUT DROP
  when: panic_mode | bool

- name: panic
  ansible.builtin.command: iptables -F
  when: panic_mode | bool
  
  # tasks file for roles/firewall_defense
